spring:
  devtools:
    restart:
      enabled: false # Mantener en false para despliegues estables
  application:
    name: minimarket-api

  # Database configuration
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 10000
      max-lifetime: 1800000      # 30 minutos
      connection-timeout: 30000
      leak-detection-threshold: 15000

  # JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: none
      multi_tenancy: SCHEMA
      multi_tenant_connection_provider: com.one.core.config.multitenancy.SchemaMultiTenantConnectionProvider
      tenant_identifier_resolver: com.one.core.config.multitenancy.JwtTenantIdentifierResolver
    show-sql: true


  flyway:
    enabled: true
    locations: classpath:db/migration/public # Solo para el schema public
    schemas: ${TENANT_SCHEMA:public}
    default-schema: ${TENANT_SCHEMA:public}

# Server configuration
server:
  port: 8080

# JWT Configuration
jwt:
  secret: ${JWT_SECRET}
  expiration.ms: 86400000
  issuer: minimarket-api
  header: Authorization
  prefix: Bearer

# Logging
logging:
  level:
    # Nivel por defecto para toda la aplicación y librerías externas.
    root: INFO

    # Nivel específico para nuestro propio código, para ver flujos.
    com.one.core: DEBUG

    # Muestra las sentencias SQL que Hibernate genera.
    org.hibernate.SQL: DEBUG

    # MUESTRA LOS VALORES DE LOS PARÁMETROS - ¡ESTA ES LA LÍNEA MÁS IMPORTANTE!
    org.hibernate.orm.jdbc.bind: TRACE

# Spring Boot Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: when_authorized
      probes:
        enabled: true

# OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    doc-expansion: none